services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    InspiredMinds\ContaoNewslistExtended\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection,ContaoNewslistExtendedBundle.php}
