services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    InspiredMinds\ContaoNewslistExtended\:
        resource: ../src

    InspiredMinds\ContaoNewslistExtended\EventListener\ExcludeCurrentNewsListener:
        tags: [{name: kernel.event_listener, event: InspiredMinds\ContaoNewsFilterEvent\Event\NewsFilterEvent}]
